name: Nightly

on: push
# on: 
#   schedule:
#     # every night at midnight
#     - cron:  '0 0 * * *'
#   workflow_dispatch:


jobs:
  # uploading master and devel tarballs to web server, for use in subsequent tests
  # the base tests that use these uploaded tarballs are the DIRAC "pilot wrapper" tests:
  # https://github.com/DIRACGrid/DIRAC/actions?query=workflow%3A%22pilot+wrapper%22
  # (triggered by https://github.com/DIRACGrid/DIRAC/blob/integration/.github/workflows/pilotWrapper.yml)
  upload:
    runs-on: ubuntu-latest
    if: github.repository == 'DIRACGrid/Pilot'

    strategy:
      fail-fast: False
      matrix:
        branch:
          - master
          - devel

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: create artifacts
        run: |
          mkdir tmp_dir
          cp Pilot/*.py tmp_dir
          cp tests/pilot.json tmp_dir
          # create the tar
          cd tmp_dir
          tar -cf pilot.tar *.py
          # make the checksums file
          sha512sum pilot.tar pilot.json *.py > checksums.sha512

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Pilot_${{ matrix.branch }}
          path: tmp_dir/pilot.tar tmp_dir/checksums.sha512
          retention-days: 2
